### ISSUE TITLE
关于multi_head_attention_2d()的参数设置

### ISSUE THREAD

**Issue by gaohuiluo** [Whu-wxy/Non-local-U-Nets-2D-block#3]
谢谢你的分享！请问在
multi_head_attention_2d(torch.nn.Module):
    def __init__(self, in_channel, key_filters, value_filters,
							output_filters, num_heads, dropout_prob=0.5, layer_type='SAME'):
中，key_filters, value_filters, num_heads的值如何确定？

**Comment by Whu-wxy** [comment]
num_heads能被key_filters和value_filters整除就行

**Comment by gaohuiluo** [comment]
谢谢回复！还有一个问题key_filters和value_filters这两个参数也是经验值吗？和input channel and output channel有关吗？这两个值对计算量影响蛮大

**Comment by Whu-wxy** [comment]
这两个参数文中没有具体说明，要看实验效果了。可以比input channel小一些，减少参数量

**Comment by gaohuiluo** [comment]
非常感谢！祝一切顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang Xinyu"<notifications@github.com&gt;; 
发送时间: 2020年6月15日(星期一) 晚上9:48
收件人: "Whu-wxy/Non-local-U-Nets-2D-block"<Non-local-U-Nets-2D-block@noreply.github.com&gt;; 
抄送: "罗高辉"<1429119168@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Whu-wxy/Non-local-U-Nets-2D-block] 关于multi_head_attention_2d()的参数设置 (#3)





 
这两个参数文中没有具体说明，要看实验效果了。可以比input channel小一些，减少参数量
